#! /bin/sh

# Copyright (c) The Exim Maintainers 1995 - 2024
# SPDX-License-Identifier: GPL-2.0-or-later

class=${CLASS:?}
classdef=${CLASSDEF:?}
drnames="${DRNAMES:?}"

# We turn the configure-built build-$foo/$class/Makefile.predynamic into Makefile.
# This is used for router and transport drivers, called from scripts/Configure-Makefile.

# We always re-exec ourselves at least once, because it's the cleanest and
# most portable way to turn on various features we expect of POSIX sh.
if [ -z "$EXIM_DRIVER_MAKEFILE_ADJUSTED" ]
then
  SHELL=/bin/sh
  EXIM_DRIVER_MAKEFILE_ADJUSTED=yes
  export EXIM_DRIVER_MAKEFILE_ADJUSTED

  # Solaris sh and tr are problematic until we get xpg4 variants
  if [ -x /usr/xpg4/bin/sh ]
  then
    PATH="/usr/xpg4/bin:$PATH"
    export PATH
    SHELL=/usr/xpg4/bin/sh
    export SHELL
  fi

  # IRIX uses /bin/ksh for sh but in a compatibility mode unless $_XPG == 1,
  # where said compatibility mode disables $(...)
  _XPG=1
  export _XPG

  # We need the _right_ tr, so must do that first; but if a shell which
  # we're more confident is sane is available, let's try that.  Mostly,
  # the problem is that "local" is not actually in "the" standard, it's
  # just in every not-insane shell.  Though arguably, there are no shells
  # with POSIX-ish syntax which qualify as "not insane".
  for b in /bin/dash /bin/bash /usr/local/bin/bash
  do
    if [ -x "$b" ]
    then
      SHELL="$b"
      break
    fi
  done
  # if we get a report of a system with zsh but not bash, we can add that
  # to the list, but be sure to enable sh_word_split in that case.

  exec "$SHELL" "$0" "$@"
fi

input=$class/Makefile.predynamic
target=$class/Makefile.postdynamic
defs_source=Makefile-t
tag_marker='MAGIC-TAG-MODS-OBJ-RULES-GO-HERE'

tab='	'

# We rely on tr(1) for translating case below.  Some people export
# values of LC_CTYPE and LC_COLLATE which apparently break our assumptions.
# We're a script expecting certain output based on known inputs and not dealing
# with UTF8, so we should be safe doing this:
LC_ALL=C
export LC_ALL

if [ -f "$defs_source" ]
then
  :
  # we are happy
else
  echo >&2 "$0: ERROR: MISSING FILE '${defs_source}'"
  echo >&2 "$0: SHOULD HAVE BEEN CALLED FROM scripts/Configure-Makefile"
  exit 1
fi

# nb: do not permit leading whitespace for this, as CFLAGS_DYNAMIC is exported
# to the lookups subdir via a line with leading whitespace which otherwise
# matches
if grep -q "^CFLAGS_DYNAMIC[ $tab?:]*=" "$defs_source"
then
  # we have a definition, we're good to go
  echo >&2 ">>> Creating $class/Makefile for building dynamic modules"
  enable_dynamic=yes
else
  echo >&2 ">>> Creating $class/Makefile without dynamic module support"
  enable_dynamic=''
  # We always do something now, since there should always be a lookup,
  # and now we need to run in order to put the OBJ=$(OBJ)+ rules in.  So we
  # continue on.
fi

# For the want_ checks, we need to let the user override values from the make
# command-line, not just check the Makefile.

want_dynamic() {
  local dyn_name="${1#_}"
  local re="(${classdef}|EXPERIMENTAL)_${dyn_name}[ $tab]*=[ $tab]*2"
  #XXX Solaris does not support -E on grep.  Must use egrep.
  env | grep -E -q "^$re"
  if [ $? -eq 0 ]; then return 0; fi
  grep -E -q "^[ $tab]*$re" "$defs_source"
}

want_not_disabled() {
  local want_name="${1#_}"
  [ "$local_want_name" = "$1" ] && return 0;
  local re="DISABLED_${want_name}[ $tab]*=[ $tab]*."
  env | grep -E -q "^$re"
  [ $? -ne 0 ] && return 0
  grep -E -q "^[ $tab]*$re" "$defs_source"
  [ $? -ne 0 ] && return 0
  return 1
}

want_at_all() {
  local want_name="$1"
  local re="(${classdef}|EXPERIMENTAL)_${want_name}[ $tab]*=[ $tab]*."
  env | grep -E -q "^$re"
  if [ $? -eq 0 ]; then return 0; fi
  grep -E -q "^[ $tab]*$re" "$defs_source"
}

# The values of these variables will be emitted into the Makefile.

MODS=""
OBJ=""

emit_module_rule() {
  local name="$1"
  local mod_name pkgconf
  if [ "${name%:*}" = "$name" ]
  then
    # Square brackets are redundant but benign for POSIX compliant tr,
    # however Solaris /usr/bin/tr requires them. Sometimes Solaris
    # gets installed without a complete set of xpg4 tools, sigh.
    mod_name=$(echo $name | tr [A-Z] [a-z])
  else
    mod_name="${name#*:}"
    name="${name%:*}"
  fi

  if want_dynamic "$name"
  then
    if [ -z "$enable_dynamic" ]; then
      echo >&2 "Missing CFLAGS_DYNAMIC prevents building dynamic $name"
      exit 1
    fi
    MODS="${MODS} ${mod_name#_}.so"
    grep "^${classdef}_${name}_PC" "$defs_source" 1>&2
    pkgconf=$(grep "^${classdef}_${name}_PC" "$defs_source")
    if [ $? -eq 0 ]; then
      pkgconf=$(echo $pkgconf | sed 's/^.*= *//')
      echo "${classdef}_${mod_name#_}_INCLUDE = $(pkg-config --cflags $pkgconf)"
      echo "${classdef}_${mod_name#_}_LIBS = $(pkg-config --libs $pkgconf)"
    else
      grep "^${classdef}_${name}_" "$defs_source"
      echo "${classdef}_${mod_name#_}_INCLUDE = \$(${classdef}_${name}_INCLUDE)"
      echo "${classdef}_${mod_name#_}_LIBS = \$(${classdef}_${name}_LIBS)"
    fi
  elif want_not_disabled "$name"; then
    OBJ="${OBJ} ${mod_name#_}.o"
  elif want_at_all "$name"; then
    OBJ="${OBJ} ${mod_name}.o"
  fi
}

rm -f "$target"
exec 5>&1
exec > "$target"

sed -n "1,/$tag_marker/p" < "$input"

for name_mod in $drnames
do
  emit_module_rule $name_mod
done

echo "MODS = $MODS"
echo "OBJ = $OBJ"

sed -n "/$tag_marker/,\$p" < "$input"

exec >&5

# Configure-Makefile will move $target into place

# vim: set ft=sh sw=2 :
