#!/bin/sh
#
# A really dumb script for making a quick tarball of Exim

set -e

OWD=$(pwd -P)

GWD=$(git rev-parse --git-dir)

TWD=$(mktemp -d -t exim) || exit 1
echo $TWD
cd $TWD

git clone $GWD

cd exim/src/src
../scripts/reversion
. version.sh
EXIM=exim-${EXIM_RELEASE_VERSION}${EXIM_VARIANT_VERSION}

cd ../..
mv src $EXIM
tar cfz $EXIM.tar.gz $EXIM
mv $EXIM src

cd $OWD
mv $TWD/exim/$EXIM.tar.gz .
rm -rf $EXIM
echo $EXIM.tar.gz
